version: '3.8'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
            - '3001:3001'

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root

        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - '3306:3306'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - '80:80'
        depends_on:
            - db
        restart: always

volumes:
    mysql_data:
